import { writeFileSync } from "node:fs";
import { CORPUS, type CorpusMelody } from "../inventory/corpus.ts";
import {
  type InventoryEntry,
  type Song,
  TIER_GLOSS,
  type Tier,
} from "../inventory/entry.ts";
import { parsePattern } from "../music/format.ts";
import { type Event, makePattern, type PatternId } from "../music/note.ts";

/**
 * Offline analysis, not app functionality: run once, check the output in. The
 * app imports the generated constant and never re-derives anything.
 */
export type DeriveOptions = {
  /** N-gram lengths to consider. v1 stops at three notes. */
  lengths: number[];
  /** Patterns rarer than this are noise, not repertoire. */
  minCount: number;
};

export const DEFAULT_OPTIONS: DeriveOptions = { lengths: [2, 3], minCount: 2 };

const TRIAD = new Set([1, 3, 5]);
const TENDENCY = new Set([4, 7]);

/**
 * Theory supplies the tiers — triad tones, then stepwise fill, then the
 * tendency tones, longer patterns after shorter ones.
 */
function tierOf(events: Event[]): Tier {
  const notes = events.flatMap((e) => e.notes);
  const hasTendency = notes.some(
    (n) => TENDENCY.has(n.degree) || n.alteration !== 0,
  );
  const hasFill = notes.some((n) => !TRIAD.has(n.degree));
  const degreeRank = hasTendency ? 2 : hasFill ? 1 : 0;
  const lengthRank = Math.min(events.length, 3) - 2;
  return (lengthRank * 3 + degreeRank) as Tier;
}

function countNgrams(
  corpus: CorpusMelody[],
  options: DeriveOptions,
): Map<
  PatternId,
  { events: Event[]; context: CorpusMelody["context"]; count: number }
> {
  const counts = new Map<
    PatternId,
    { events: Event[]; context: CorpusMelody["context"]; count: number }
  >();
  for (const song of corpus) {
    const parsed = parsePattern(song.melody, song.context);
    if (!parsed.ok) throw new Error(`${song.id}: ${parsed.error}`);
    const events = parsed.value.events;
    for (const n of options.lengths) {
      for (let i = 0; i + n <= events.length; i++) {
        const window = events.slice(i, i + n);
        const pattern = makePattern(song.context, window);
        const existing = counts.get(pattern.id);
        if (existing) existing.count++;
        else
          counts.set(pattern.id, {
            events: pattern.events,
            context: song.context,
            count: 1,
          });
      }
    }
  }
  return counts;
}

/** Repeated-note "patterns" are not intervals; they teach nothing. */
function isRepeatedNote(events: Event[]): boolean {
  const first = JSON.stringify(events[0]);
  return events.every((e) => JSON.stringify(e) === first);
}

export function deriveInventory(
  corpus: CorpusMelody[],
  options: DeriveOptions = DEFAULT_OPTIONS,
): InventoryEntry[] {
  const entries: InventoryEntry[] = [];
  for (const [id, { events, count }] of countNgrams(corpus, options)) {
    if (count < options.minCount) continue;
    if (isRepeatedNote(events)) continue;
    const tier = tierOf(events);
    entries.push({
      id,
      tier,
      count,
      gloss: TIER_GLOSS[tier],
    });
  }
  return entries.sort(
    (a, b) => a.tier - b.tier || b.count - a.count || (a.id < b.id ? -1 : 1),
  );
}

/**
 * Greedy longest-match tiling of a melody against the inventory: prefer the
 * longest entry that starts here, and if nothing matches, skip the note. Skips
 * are why this is a decomposition rather than a lossless factorization — a note
 * the corpus never repeats has no pattern to belong to.
 */
export function decompose(
  melody: CorpusMelody,
  known: Set<PatternId>,
  options: DeriveOptions = DEFAULT_OPTIONS,
): PatternId[] {
  const parsed = parsePattern(melody.melody, melody.context);
  if (!parsed.ok) throw new Error(`${melody.id}: ${parsed.error}`);
  const events = parsed.value.events;
  const lengths = [...options.lengths].sort((a, b) => b - a);
  const out: PatternId[] = [];
  let i = 0;
  while (i < events.length) {
    const hit = lengths
      .filter((n) => i + n <= events.length)
      .map((n) => ({
        n,
        id: makePattern(melody.context, events.slice(i, i + n)).id,
      }))
      .find(({ id }) => known.has(id));
    if (hit) {
      out.push(hit.id);
      i += hit.n;
    } else {
      i += 1;
    }
  }
  return out;
}

export function deriveSongs(
  corpus: CorpusMelody[],
  inventory: InventoryEntry[],
  options: DeriveOptions = DEFAULT_OPTIONS,
): Song[] {
  const known = new Set(inventory.map((e) => e.id));
  return corpus.map((melody) => ({
    id: melody.id,
    title: melody.title,
    context: melody.context,
    patternIds: decompose(melody, known, options),
  }));
}

function render(entries: InventoryEntry[]): string {
  const rows = entries
    .map(
      (e) =>
        `  { id: ${JSON.stringify(e.id)} as PatternId, tier: ${e.tier}, count: ${e.count}, gloss: ${JSON.stringify(e.gloss)} },`,
    )
    .join("\n");
  return [
    "// Generated by scripts/derive-inventory.ts. Do not edit by hand.",
    'import type { InventoryEntry } from "./entry.ts";',
    'import type { PatternId } from "../music/note.ts";',
    "",
    "export const INVENTORY: InventoryEntry[] = [",
    rows,
    "];",
    "",
  ].join("\n");
}

function renderSongs(songs: Song[]): string {
  const rows = songs
    .map(
      (s) =>
        `  { id: ${JSON.stringify(s.id)}, title: ${JSON.stringify(s.title)}, context: ${JSON.stringify(s.context)}, patternIds: ${JSON.stringify(s.patternIds)} as PatternId[] },`,
    )
    .join("\n");
  return [
    "// Generated by scripts/derive-inventory.ts. Do not edit by hand.",
    'import type { Song } from "./entry.ts";',
    'import type { PatternId } from "../music/note.ts";',
    "",
    "export const SONGS: Song[] = [",
    rows,
    "];",
    "",
  ].join("\n");
}

function main(): void {
  const inventory = deriveInventory(CORPUS);
  writeFileSync(
    new URL("../inventory/patterns.ts", import.meta.url),
    render(inventory),
  );
  writeFileSync(
    new URL("../inventory/songs.ts", import.meta.url),
    renderSongs(deriveSongs(CORPUS, inventory)),
  );
}

if (process.argv[1]?.includes("derive-inventory")) main();
