import { writeFileSync } from "node:fs";
import { CORPUS, type CorpusMelody } from "../inventory/corpus.ts";
import {
  type InventoryEntry,
  TIER_GLOSS,
  type Tier,
} from "../inventory/entry.ts";
import { parsePattern } from "../music/format.ts";
import { type Event, makePattern, type PatternId } from "../music/note.ts";

/**
 * Offline analysis, not app functionality: run once, check the output in. The
 * app imports the generated constant and never re-derives anything.
 */
export type DeriveOptions = {
  /** N-gram lengths to consider. v1 stops at three notes. */
  lengths: number[];
  /** Patterns rarer than this are noise, not repertoire. */
  minCount: number;
};

export const DEFAULT_OPTIONS: DeriveOptions = { lengths: [2, 3], minCount: 2 };

const TRIAD = new Set([1, 3, 5]);
const TENDENCY = new Set([4, 7]);

/**
 * Theory supplies the tiers — triad tones, then stepwise fill, then the
 * tendency tones, longer patterns after shorter ones.
 */
function tierOf(events: Event[]): Tier {
  const notes = events.flatMap((e) => e.notes);
  const hasTendency = notes.some(
    (n) => TENDENCY.has(n.degree) || n.alteration !== 0,
  );
  const hasFill = notes.some((n) => !TRIAD.has(n.degree));
  const degreeRank = hasTendency ? 2 : hasFill ? 1 : 0;
  const lengthRank = Math.min(events.length, 3) - 2;
  return (lengthRank * 3 + degreeRank) as Tier;
}

function countNgrams(
  corpus: CorpusMelody[],
  options: DeriveOptions,
): Map<
  PatternId,
  { events: Event[]; context: CorpusMelody["context"]; count: number }
> {
  const counts = new Map<
    PatternId,
    { events: Event[]; context: CorpusMelody["context"]; count: number }
  >();
  for (const song of corpus) {
    const parsed = parsePattern(song.melody, song.context);
    if (!parsed.ok) throw new Error(`${song.id}: ${parsed.error}`);
    const events = parsed.value.events;
    for (const n of options.lengths) {
      for (let i = 0; i + n <= events.length; i++) {
        const window = events.slice(i, i + n);
        const pattern = makePattern(song.context, window);
        const existing = counts.get(pattern.id);
        if (existing) existing.count++;
        else
          counts.set(pattern.id, {
            events: pattern.events,
            context: song.context,
            count: 1,
          });
      }
    }
  }
  return counts;
}

/** Repeated-note "patterns" are not intervals; they teach nothing. */
function isRepeatedNote(events: Event[]): boolean {
  const first = JSON.stringify(events[0]);
  return events.every((e) => JSON.stringify(e) === first);
}

export function deriveInventory(
  corpus: CorpusMelody[],
  options: DeriveOptions = DEFAULT_OPTIONS,
): InventoryEntry[] {
  const entries: InventoryEntry[] = [];
  for (const [id, { events, count }] of countNgrams(corpus, options)) {
    if (count < options.minCount) continue;
    if (isRepeatedNote(events)) continue;
    const tier = tierOf(events);
    entries.push({
      id,
      tier,
      count,
      gloss: `${TIER_GLOSS[tier]} — ${count} occurrences in the corpus`,
    });
  }
  return entries.sort(
    (a, b) => a.tier - b.tier || b.count - a.count || (a.id < b.id ? -1 : 1),
  );
}

function render(entries: InventoryEntry[]): string {
  const rows = entries
    .map(
      (e) =>
        `  { id: ${JSON.stringify(e.id)} as PatternId, tier: ${e.tier}, count: ${e.count}, gloss: ${JSON.stringify(e.gloss)} },`,
    )
    .join("\n");
  return [
    "// Generated by scripts/derive-inventory.ts. Do not edit by hand.",
    'import type { InventoryEntry } from "./entry.ts";',
    'import type { PatternId } from "../music/note.ts";',
    "",
    "export const INVENTORY: InventoryEntry[] = [",
    rows,
    "];",
    "",
  ].join("\n");
}

function main(): void {
  const out = new URL("../inventory/patterns.ts", import.meta.url);
  writeFileSync(out, render(deriveInventory(CORPUS)));
}

if (process.argv[1]?.includes("derive-inventory")) main();
